init:
  - git config --global core.autocrlf true
 
image: Visual Studio 2017
 
before_build:
- choco install opencover.portable
- choco install codecov
 
build_script:
  - ps: .\build.ps1
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full test\Finance.Domain.Tests\Finance.Domain.Tests.csproj" -filter:"+[Finance.Domain*]* -[Finance.Domain.Tests*]*" -output:".\my_app_coverage.xml"
  - codecov -f .\valit_coverage.xml -t $(codecov_token)
 
test: off
 
branches:
  only:
    - dev
    - master
 
cache:
- tools -> build.cake
- packages -> build.cake